library("rtracklayer")
library("ballgown")
library("sSeq")
library("DESeq2")
library("pheatmap")
library("gplots")
library("ggplot2")
library("reshape2")
library("biomaRt")
library("PoiClaClu")
library("pathview")
library("GOplot")
library("circlize")

source(".../heatmap.3.R")
source(".../misc_rnaseq_funcs.R")
source(".../pairs3.R")